// Generated by ts-to-zod
import { z } from "zod";

export const GetArticleByIdQuery = z.object({
  __typename: z.literal("query_root").optional(),
  article: z
    .object({
      __typename: z.literal("news_feeds").optional(),
      uuid: z.string(),
      title: z.string(),
      text: z.string(),
      created_at: z.string(),
      news_comments: z.array(
        z.object({
          __typename: z.literal("news_comments").optional(),
          uuid: z.string(),
          text: z.string(),
          created_at: z.string(),
        })
      ),
    })
    .optional()
    .nullable(),
});

export const SendCommentMutation = z.object({
  __typename: z.literal("mutation_root").optional(),
  insert_news_comments_one: z
    .object({
      __typename: z.literal("news_comments").optional(),
      uuid: z.string(),
    })
    .optional()
    .nullable(),
});

export const LastCommentForArticleByIdSubscription = z.object({
  __typename: z.literal("subscription_root").optional(),
  news_comments: z.array(
    z.object({
      __typename: z.literal("news_comments").optional(),
      uuid: z.string(),
    })
  ),
});

export const GetNewsFeedListQuery = z.object({
  __typename: z.literal("query_root").optional(),
  news_feeds: z.array(
    z.object({
      __typename: z.literal("news_feeds").optional(),
      uuid: z.string(),
      title: z.string(),
      created_at: z.string(),
    })
  ),
});
